- name: Configuring NTP with timesync role
  ansible.builtin.include_role:
    name: redhat.rhel_system_roles.timesync
  vars:
    timesync_ntp_servers:
    - hostname: a.st1.ntp.br
      trusted: yes
      prefer: yes
      iburst: yes
    - hostname: b.st1.ntp.br
      pool: yes
      iburst: yes
    - hostname: c.st1.ntp.br
      pool: yes
      iburst: yes