- name: Adicionar host ao grupo mclinux
  add_host:
    name: "{{ ipfree.json.data }}"
    groups: mclinux
    ansible_host: "{{ ipfree.json.data }}"
    ansible_user: root
    ansible_connection: ssh